name: CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install dependencies
        run: yarn
      - name: Compile
        run: yarn tsc
      - name: Lint
        run: yarn lint
      - name: Migration
        env:
          DATABASE_URL: ${{ secrets.MIGRATION_DB_URL }}
        run: yarn prisma migrate deploy
